# Generated by Django 4.2 on 2023-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ANALISES', 'Análises'), ('PROGRAMACAO', 'Programação'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros'), ('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('DRAMA', 'Drama'), ('TERROR', 'Terror')], max_length=15),
        ),
    ]
